{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tempest-exporter.fullname" . }}
  labels:
    {{- include "tempest-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempest-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
{{- end }}
